config/routes.rb
Rails.application.routes.draw do
  # read - list all restaurants
  get 'restaurants', to: 'restaurants#index'

  # create - add a restaurant
  get 'restaurants/new', to: 'restaurants#new', as: :new_restaurant # form page
  post 'restaurants', to: 'restaurants#create' # create restaurant in DB

  # read - show one particular restaurant
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant

  # update - update a particular restaurant
  get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant # form page
  patch "restaurants/:id", to: "restaurants#update" # update restaurant in DB

  # delete - delete a particular restaurant
  delete "restaurants/:id", to: "restaurants#destroy"

  # resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all.reverse
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Spoon | A Restaurant Guide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>The Spoon | A Restaurant Guide</h1>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>

<%= render 'form', restaurant: @restaurant %>
<p><%= link_to 'Cancel', restaurant_path(@restaurant) %></p>

app/views/restaurants/index.html.erb
<h2>All Restaurants</h2>

<p><%= link_to 'Add Restaurant', new_restaurant_path %></p>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><h3><%= link_to restaurant.name, restaurant_path(restaurant) %> <%= '⭐️'*restaurant.rating %><h3></li>
    <p><%= restaurant.address %></p>
    <p>
      <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
      <%= link_to 'Delete', restaurant_path(restaurant), method: :delete, data: {confirm: "Are you sure?" } %>
    </p>
    <hr/>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<h2>Add Restaurant</h2>

<%= render 'form', restaurant: @restaurant %>
<p><%= link_to 'Cancel', restaurants_path %></p>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %> <%= '⭐️'*@restaurant.rating %></h2>
<p><%= @restaurant.address %></p>
<p><%= link_to 'Edit', edit_restaurant_path(@restaurant) %> <%= link_to 'Delete', restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %></p>
<p><%= link_to 'All Restaurants', restaurants_path %></p>